name: MINLP
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.3', '1']  # Test against current minor release (at least 1.3)
        os: [ubuntu-latest, macOS-latest]
        arch: [x64]
    steps:
      - shell: bash
        run: |
          julia 
            using Pkg; Pkg.develop(pwd(SCIP))
            using Pkg; Pkg.activate(test/MINLPTest)
            include run_minlptests.jl